#!/usr/bin/env python3
"""Inject Reflexion memories into agent context based on current profile and mode.

Usage:
    python scripts/inject_memory.py --profile coding --mode autonomous
    python scripts/inject_memory.py --profile coding --mode project --max 3

Output: Markdown-formatted memories ready for injection into system prompt.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

REFLECTIONS_DIR = Path(__file__).resolve().parent.parent / "memory" / "reflections"


def load_reflections(profile: str) -> list[dict]:
    """Load all reflection records for a profile from JSONL files."""
    records: list[dict] = []
    if not REFLECTIONS_DIR.exists():
        return records

    for f in sorted(REFLECTIONS_DIR.glob(f"{profile}_*.jsonl")):
        with f.open("r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return records


def rank_reflections(records: list[dict], profile: str, mode: str) -> list[dict]:
    """Score and rank reflections by relevance to current profile + mode.

    Scoring (higher = more relevant):
        - Same profile: +3
        - Same mode: +2
        - Resolved: +1
        - Higher severity (P0 > P1 > P2): +2/+1/0
        - Recency (newer = higher): scaled 0-2
    """
    severity_score = {"P0": 2, "P1": 1, "P2": 0}

    def score(r: dict) -> float:
        s = 0.0
        if r.get("profile") == profile:
            s += 3
        if r.get("agent_mode") == mode:
            s += 2
        if r.get("metadata", {}).get("resolved", False):
            s += 1
        s += severity_score.get(r.get("lesson", {}).get("severity", "P2"), 0)
        # Recency: scale timestamp age 0-2 (newer = higher)
        ts = r.get("timestamp", "")
        if ts:
            try:
                dt = datetime.fromisoformat(ts)
                age_days = (datetime.now(timezone.utc) - dt).days
                s += max(0, 2 - age_days / 30)  # Full score if < 30 days, decays
            except (ValueError, TypeError):
                pass
        return s

    return sorted(records, key=score, reverse=True)


def format_memories(records: list[dict], max_count: int) -> str:
    """Format top-N records as Markdown for injection."""
    if not records:
        return ""

    lines = [
        "<!-- Reflexion Memory Injection (auto-generated by inject_memory.py) -->",
        "## Past Reflections (past reflections / 过往反思教训)",
        "",
        "The following are lessons learned from previous sessions. Apply these proactively.",
        "",
    ]

    for i, r in enumerate(records[:max_count], 1):
        lesson = r.get("lesson", {})
        trigger = r.get("trigger", {})
        lines.append(f"### Reflection {i}: {lesson.get('pattern', 'Unknown Pattern')}")
        lines.append(f"- **Trigger**: {trigger.get('description', 'N/A')}")
        lines.append(f"- **Lesson**: {lesson.get('rule', 'N/A')}")
        lines.append(f"- **Severity**: {lesson.get('severity', 'P2')}")
        lines.append(f"- **Applies to**: {', '.join(lesson.get('applies_to', []))}")
        lines.append(f"- **Session**: {r.get('session_id', 'unknown')}")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Inject reflexion memories")
    parser.add_argument("--profile", required=True, help="Current profile (e.g., coding)")
    parser.add_argument("--mode", default="project", help="Current agent mode")
    parser.add_argument("--max", type=int, default=5, help="Max memories to inject")
    args = parser.parse_args()

    records = load_reflections(args.profile)
    ranked = rank_reflections(records, args.profile, args.mode)
    output = format_memories(ranked, args.max)
    print(output)


if __name__ == "__main__":
    main()
