#!/usr/bin/env python3
"""AgentSeed trae PreToolUse Hook.

Auto-generated by agentseed platform import.
Core logic: calls decide() from adapters/hooks/shared/check.py.
"""
from __future__ import annotations
import json, sys
from pathlib import Path

_HOOKS_DIR = Path(__file__).resolve().parent.parent
_SHARED = _HOOKS_DIR / "shared"
sys.path.insert(0, str(_SHARED))
from check import decide

def main():
    try:
        raw = sys.stdin.read()
        if not raw.strip():
            print(json.dumps({"allow": True}))
            return
        data = json.loads(raw)
    except (json.JSONDecodeError, ValueError):
        print(json.dumps({"allow": True}))
        return

    tool_name = data.get("tool_name") or data.get("toolName", "")
    tool_input = data.get("tool_input") or data.get("toolInput", {})

    try:
        result = decide(tool_name, tool_input)
    except Exception:
        print(json.dumps({"allow": True}))
        return

    if result.get("deny"):
        print(json.dumps({"deny": True, "reason": result["reason"]}))
        return
    if result.get("require_approval"):
        print(json.dumps({"requireApproval": True, "reason": result["reason"]}))
        return
    if result.get("warn"):
        print(json.dumps({"warn": result["warn"]}))
        return

    print(json.dumps({"allow": True}))

if __name__ == "__main__":
    main()
